# Generated by Django 4.2.7 on 2025-06-20 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_type', models.CharField(choices=[('view', '查看'), ('add', '添加'), ('edit', '编辑'), ('delete', '删除'), ('export', '导出'), ('team', '团队变更'), ('login', '登录'), ('other', '其它')], max_length=20, verbose_name='操作类型')),
                ('object_repr', models.CharField(max_length=255, verbose_name='对象描述')),
                ('detail', models.TextField(blank=True, verbose_name='详情')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('result', models.CharField(max_length=20, verbose_name='结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
