# Generated by Django 4.2.7 on 2025-06-16 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('website', models.URLField(blank=True, verbose_name='网站')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('encrypted_password', models.BinaryField(verbose_name='加密密码')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('salt', models.BinaryField(max_length=32, verbose_name='盐值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_entries', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='所属团队')),
            ],
            options={
                'verbose_name': '密码条目',
                'verbose_name_plural': '密码条目',
                'ordering': ['-updated_at'],
            },
        ),
    ]
